
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Solicitante','com_ouvidoria.solicitante','{"special":{"dbtable":"#__ouvidoria_solicitantes","key":"id","type":"Solicitante","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitante.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_associado","targetTable":"#__associados","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_user","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.solicitante')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Solicitante', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_solicitantes","key":"id","type":"Solicitante","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitante.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_associado","targetTable":"#__associados","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_user","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.solicitante');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Solicitação','com_ouvidoria.solicitacao','{"special":{"dbtable":"#__ouvidoria_solicitacoes","key":"id","type":"Solicitacao","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacao.xml", "hideFields":["checked_out","checked_out_time","params","language" ,"anexo"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_solicitante","targetTable":"#__ouvidoria_solicitantes","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_tipo","targetTable":"#__ouvidoria_solicitacoes_tipos","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_diretoria_responsavel","targetTable":"#__ouvidoria_diretorias","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"status","targetTable":"#__ouvidoria_solicitacoes_status","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_user_responsavel_atual","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.solicitacao')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Solicitação', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_solicitacoes","key":"id","type":"Solicitação","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacao.xml", "hideFields":["checked_out","checked_out_time","params","language" ,"anexo"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_solicitante","targetTable":"#__ouvidoria_solicitantes","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_tipo","targetTable":"#__ouvidoria_solicitacoes_tipos","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_diretoria_responsavel","targetTable":"#__ouvidoria_diretorias","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"status","targetTable":"#__ouvidoria_solicitacoes_status","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_user_responsavel_atual","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.solicitacao');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Tipo (solicitação)','com_ouvidoria.solicitacaotipo','{"special":{"dbtable":"#__ouvidoria_solicitacoes_tipos","key":"id","type":"Solicitacaotipo","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaotipo.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.solicitacaotipo')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Tipo (solicitação)', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_solicitacoes_tipos","key":"id","type":"Tipo (solicitação)","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaotipo.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.solicitacaotipo');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Status (solicitação)','com_ouvidoria.solicitacaostatus','{"special":{"dbtable":"#__ouvidoria_solicitacoes_status","key":"id","type":"Solicitacaostatus","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaostatus.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.solicitacaostatus')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Status (solicitação)', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_solicitacoes_status","key":"id","type":"Status (solicitação)","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaostatus.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.solicitacaostatus');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Interação (solicitação)','com_ouvidoria.solicitacaointeracao','{"special":{"dbtable":"#__ouvidoria_solicitacoes_interacoes","key":"id","type":"Solicitacaointeracao","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaointeracao.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.solicitacaointeracao')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Interação (solicitação)', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_solicitacoes_interacoes","key":"id","type":"Interação (solicitação)","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaointeracao.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.solicitacaointeracao');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Diretoria','com_ouvidoria.diretoria','{"special":{"dbtable":"#__ouvidoria_diretorias","key":"id","type":"Diretoria","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/diretoria.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.diretoria')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Diretoria', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_diretorias","key":"id","type":"Diretoria","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/diretoria.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.diretoria');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Usuário resposável (Diretoria)','com_ouvidoria.diretoriasuserresponsavel','{"special":{"dbtable":"#__ouvidoria_diretorias_users_responsaveis","key":"id","type":"Diretoriasuserresponsavel","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/diretoriasuserresponsavel.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_diretoria","targetTable":"#__ouvidoria_diretorias","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_user","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.diretoriasuserresponsavel')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Usuário resposável (Diretoria)', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_diretorias_users_responsaveis","key":"id","type":"Usuário resposável (Diretoria)","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/diretoriasuserresponsavel.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_diretoria","targetTable":"#__ouvidoria_diretorias","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_user","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.diretoriasuserresponsavel');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Log (solicitação)','com_ouvidoria.solicitacaolog','{"special":{"dbtable":"#__ouvidoria_solicitacoes_logs","key":"id","type":"Solicitacaolog","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaolog.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"created_by_solicitante","targetTable":"#__ouvidoria_solicitantes","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_solicitacao","targetTable":"#__ouvidoria_solicitacoes","targetColumn":"id","displayColumn":"protocolo"},{"sourceColumn":"id_interacao","targetTable":"#__ouvidoria_solicitacoes_interacoes","targetColumn":"id","displayColumn":"nome"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.solicitacaolog')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Log (solicitação)', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_solicitacoes_logs","key":"id","type":"Log (solicitação)","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/solicitacaolog.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"created_by_solicitante","targetTable":"#__ouvidoria_solicitantes","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_solicitacao","targetTable":"#__ouvidoria_solicitacoes","targetColumn":"id","displayColumn":"protocolo"},{"sourceColumn":"id_interacao","targetTable":"#__ouvidoria_solicitacoes_interacoes","targetColumn":"id","displayColumn":"nome"}]}'
WHERE (`type_alias` = 'com_ouvidoria.solicitacaolog');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Comentário','com_ouvidoria.comentario','{"special":{"dbtable":"#__ouvidoria_comentarios","key":"id","type":"Comentario","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/comentario.xml", "hideFields":["checked_out","checked_out_time","params","language" ,"anexo"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"created_by_solicitante","targetTable":"#__ouvidoria_solicitantes","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_solicitacao","targetTable":"#__ouvidoria_solicitacoes","targetColumn":"id","displayColumn":"protocolo"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.comentario')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Comentário', 
	`table` = '{"special":{"dbtable":"#__ouvidoria_comentarios","key":"id","type":"Comentário","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/comentario.xml", "hideFields":["checked_out","checked_out_time","params","language" ,"anexo"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"created_by_solicitante","targetTable":"#__ouvidoria_solicitantes","targetColumn":"id","displayColumn":"nome"},{"sourceColumn":"id_solicitacao","targetTable":"#__ouvidoria_solicitacoes","targetColumn":"id","displayColumn":"protocolo"}]}'
WHERE (`type_alias` = 'com_ouvidoria.comentario');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Associado','com_ouvidoria.associado','{"special":{"dbtable":"#__associados","key":"id","type":"Associado","prefix":"UvidoriaTable"}}', '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/associado.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ouvidoria.associado')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Associado', 
	`table` = '{"special":{"dbtable":"#__associados","key":"id","type":"Associado","prefix":"UvidoriaTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ouvidoria\/models\/forms\/associado.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ouvidoria.associado');
